plugins:
  resenha_enabled:
    default: false
    client: true
  resenha_allow_trust_level:
    default: 2
    min: 0
    max: 4
  resenha_max_rooms_per_user:
    default: 5
  resenha_participant_ttl_seconds:
    default: 30
  resenha_stun_servers:
    default: "stun:stun.l.google.com:19302|stun:global.stun.twilio.com:3478"
    client: true
  resenha_turn_servers:
    default: ""
    client: true
  resenha_turn_username:
    default: ""
    client: true
  resenha_turn_credential:
    default: ""
    client: true
    secret: true
